workspace(name = "tink_java_gcpkms_examples")

local_repository(
    name = "tink_java_gcpkms",
    path = "..",
)

load("@tink_java_gcpkms//:tink_java_gcpkms_deps.bzl", "TINK_JAVA_GCPKMS_MAVEN_ARTIFACTS", "tink_java_gcpkms_deps")

tink_java_gcpkms_deps()

load("@tink_java//:tink_java_deps.bzl", "tink_java_deps", "TINK_MAVEN_ARTIFACTS")

tink_java_deps()

load("@tink_java//:tink_java_deps_init.bzl", "tink_java_deps_init")

tink_java_deps_init()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = TINK_MAVEN_ARTIFACTS +
    TINK_JAVA_GCPKMS_MAVEN_ARTIFACTS + [
      "args4j:args4j:2.33",
      "com.google.cloud:google-cloud-storage:2.28.0",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
